# Use C++ build environment.
language: cpp

# Protobuf requires g++ (see https://github.com/google/protobuf/blob/master/src/README.md)
compiler:
    - gcc

# Cache dependencies to speed up the build.
cache:
    directories:
        - ${TRAVIS_BUILD_DIR}/deps/protobuf

# Handle dependencies in separate directory.
before_install:
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - mkdir -p "${DEPS_DIR}"
    - cd "${DEPS_DIR}"

install:
    # Install a recent version of the Protobuf
    - |
        PROTOBUF_URL="https://github.com/google/protobuf/releases/download/v3.2.0/protobuf-cpp-3.2.0.tar.gz"
        if [ ! -f ${DEPS_DIR}/protobuf/install/bin/protoc ] ; then mkdir -p protobuf ; travis_retry wget --no-check-certificate --quiet -O - ${PROTOBUF_URL} | tar --strip-components=1 -xz -C protobuf ; cd protobuf ; ./configure --prefix=${DEPS_DIR}/protobuf/install ; make ; make install ; fi
        export PATH=${DEPS_DIR}/protobuf/install/bin:${PATH}
    - |
        cd ${DEPS_DIR}
        git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc
        cd grpc
        git submodule update --init
        make
        make prefix=${DEPS_DIR}/grpc/install/bin install

# Change directory back to default build directory.
before_script:
    - cd "${TRAVIS_BUILD_DIR}"

# Run the build script.
script:
    - mkdir -p bin
    - make clean
    - export LD_LIBRARY_PATH=${DEPS_DIR}/grpc/libs/opt:$LD_LIBRARY_PATH
    - export PATH=${DEPS_DIR}/grpc/bins/opt:$PATH
    - make print-GRPC_CPP_PLUGIN_PATH
    - make
